const jwt = require('jsonwebtoken');

const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsImZpcnN0bmFtZSI6IkFiaWdhZWwiLCJsYXN0bmFtZSI6Ildhc2FiaSIsImVtYWlsIjoiYWJpd2FzYWJpMDNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkVEdBY3dqYjRTenJCMDFOMW9aTTdtLkNXMkJybHVJd1JNM3ZHczJsWVpOUVJQaFVzU01oUzYiLCJpYXQiOjE3MDE1NTE2NDUsImV4cCI6MTcwMTU1NTI0NX0.NDYW1WiY6j7mYOsi9NPDZIXS0sZbczlyllk-PvROyjs";
 

const decoded = jwt.decode(token);

console.log(decoded);
